

all: Mensagem.class ConexaoCliente.class Servidor.class


Mensagem.class: Mensagem.java
	javac Mensagem.java

ConexaoCliente.class: ConexaoCliente.java
	javac ConexaoCliente.java

Servidor.class: Servidor.java
	javac Servidor.java

clean:
	rm -fv *.backup* *.class

